"use client";
import React from "react";
import CountUp from "react-countup";

export default function StatsSections() {
  return (
    <div
      className="bg-gray-50 p-8 min-h-[350px] flex flex-col items-center justify-center 
    font-[sans-serif] text-[#333]"
    >
      <div className="max-w-screen-2xl mx-auto px-3">
        <h2 className="text-3xl font-bold mb-14 text-center">
          Application Metrics
        </h2>
        <div className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
          <div className="text-center">
            <h3 className="text-4xl font-extrabold">
              <CountUp end={5.4} decimals={1} duration={2.5} />
              M+
            </h3>
            <p className="text-base font-bold mt-3">Total Users</p>
            <p className="text-sm text-gray-500 mt-2">
              The total number of registered users on the platform.
            </p>
          </div>
          <div className="text-center">
            <h3 className="text-4xl font-extrabold">
              <CountUp end={80} duration={2.5} />K
            </h3>
            <p className="text-base font-bold mt-3">Revenue</p>
            <p className="text-sm text-gray-500 mt-2">
              The total revenue generated by the application.
            </p>
          </div>
          <div className="text-center">
            <h3 className="text-4xl font-extrabold">
              <CountUp end={100} duration={2.5} />K
            </h3>
            <p className="text-base font-bold mt-3">Engagement</p>
            <p className="text-sm text-gray-500 mt-2">
              The level of user engagement with the application&apos;s content
              and features.
            </p>
          </div>
          <div className="text-center">
            <h3 className="text-4xl font-extrabold">
              <CountUp end={99.9} decimals={1} duration={2.5} />%
            </h3>
            <p className="text-base font-bold mt-3">Server Uptime</p>
            <p className="text-sm text-gray-500 mt-2">
              The percentage of time the server has been operational and
              available.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
